site_name: Test of MkDocs
pages:
    - Home: 'index.md'
    - First: 'first.md'
    - Second: 'second.md'
    - Third: 'third.md'
    - Fourth: '../sources/fourth.md'
theme: 'readthedocs'
repo_url: https://github.com/tombaker/test
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'Test of MkDocs'
